language: node_js
node_js:
  - 6
services:
  - mongodb
before_script:
  - npm install -g coveralls
script:
  - npm run jshint
  - npm run coverage
after_script:
  - cat ./coverage/lcov.info | coveralls
